title: "Brock Kaess"
author: "Brock Kaess"
description: "Colorado State University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "README.md", icon: "home"}
  - {file: "index.html", icon: "archive"}
  - {file: "resume.md", icon: "file"}
  - {file: "rocket-league.md", icon: "gamepad"}
  - {file: "cat.md", title: "Cat", icon: "cat"}
  - {file: "misc.md", icon: "file-archive"}
#  url: "brocklli.github.io/nav/music.md",


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:kaess2017@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/Brocklli"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/brock-kaess/"}
  - {file: "faq.md", icon: "question"}

comments:
  # disqus_shortname: ""    # see https://disqus.com/
  # isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-redirect-from